CREATE TABLE STUDENT_MASTER
(
	student_id SERIAL PRIMARY KEY,
	login_id VARCHAR NOT NULL UNIQUE,
	password VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	gender INTEGER NOT NULL,
	birthday DATE NOT NULL
);

CREATE TABLE PROFESSOR_MASTER
(
	professor_id SERIAL PRIMARY KEY,
	login_id VARCHAR NOT NULL UNIQUE,
	password VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	gender INTEGER NOT NULL
);

CREATE TABLE COURSE_MASTER
(
	course_id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	professor_id INTEGER REFERENCES PROFESSOR_MASTER(professor_id) NOT NULL
);

CREATE TABLE STUDENT_TO_COURSE
(
	student_id INTEGER REFERENCES STUDENT_MASTER(student_id),
	course_id INTEGER REFERENCES COURSE_MASTER(course_id),
	PRIMARY KEY(student_id, course_id)
);